// <auto-generated />
using System;
using F1Fantasy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Fantasy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703151332_AddDynamicPricing")]
    partial class AddDynamicPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1Fantasy.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JolpicaConstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Constructors");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ConstructorId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetCap")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasUsedTransfer")
                        .HasColumnType("bit");

                    b.Property<decimal>("LockedInPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RemainingBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamConstructor", b =>
                {
                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<decimal>("PointsAtTransfer")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FantasyTeamId", "ConstructorId");

                    b.HasIndex("ConstructorId");

                    b.ToTable("FantasyTeamConstructors");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamDriver", b =>
                {
                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("PointsAtTransfer")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FantasyTeamId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("FantasyTeamDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.LeagueMember", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMembers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsScored")
                        .HasColumnType("bit");

                    b.Property<int>("P1DriverId")
                        .HasColumnType("int");

                    b.Property<int>("P2DriverId")
                        .HasColumnType("int");

                    b.Property<int>("P3DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ScoredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("P1DriverId");

                    b.HasIndex("P2DriverId");

                    b.HasIndex("P3DriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId", "RaceId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoundNumber")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResultDriver", b =>
                {
                    b.Property<int>("RaceResultId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("DidFinish")
                        .HasColumnType("bit");

                    b.Property<decimal>("FantasyPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("FastestLap")
                        .HasColumnType("bit");

                    b.Property<int>("Grid")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("RaceResultId", "DriverId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.ToTable("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.TeamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId", "RaceId")
                        .IsUnique();

                    b.ToTable("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("Drivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", null)
                        .WithMany("FantasyTeams")
                        .HasForeignKey("ConstructorId");

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithOne("FantasyTeam")
                        .HasForeignKey("F1Fantasy.Api.Models.FantasyTeam", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamConstructor", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("FantasyTeamConstructors")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamConstructors")
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamDriver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Driver", "Driver")
                        .WithMany("FantasyTeamDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamDrivers")
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.League", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.AppUser", "Owner")
                        .WithMany("OwnedLeagues")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.LeagueMember", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Prediction", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Driver", "P1Driver")
                        .WithMany()
                        .HasForeignKey("P1DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.Driver", "P2Driver")
                        .WithMany()
                        .HasForeignKey("P2DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.Driver", "P3Driver")
                        .WithMany()
                        .HasForeignKey("P3DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.Race", "Race")
                        .WithMany("Predictions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("P1Driver");

                    b.Navigation("P2Driver");

                    b.Navigation("P3Driver");

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.PriceHistory", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("F1Fantasy.Api.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Constructor");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Race", "Race")
                        .WithOne("RaceResult")
                        .HasForeignKey("F1Fantasy.Api.Models.RaceResult", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResultDriver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("RaceResultDrivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.Driver", "Driver")
                        .WithMany("RaceResultDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.RaceResult", "RaceResult")
                        .WithMany("DriverResults")
                        .HasForeignKey("RaceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Driver");

                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.TeamScore", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Race", "Race")
                        .WithMany("TeamScores")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithMany("TeamScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.AppUser", b =>
                {
                    b.Navigation("FantasyTeam");

                    b.Navigation("LeagueMemberships");

                    b.Navigation("OwnedLeagues");

                    b.Navigation("Predictions");

                    b.Navigation("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Constructor", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("FantasyTeamConstructors");

                    b.Navigation("FantasyTeams");

                    b.Navigation("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.Navigation("FantasyTeamDrivers");

                    b.Navigation("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.Navigation("FantasyTeamConstructors");

                    b.Navigation("FantasyTeamDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.League", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Race", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("RaceResult");

                    b.Navigation("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.Navigation("DriverResults");
                });
#pragma warning restore 612, 618
        }
    }
}
