// <auto-generated />
using System;
using F1Fantasy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Fantasy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1Fantasy.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Constructors");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ConstructorId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetCap")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RemainingBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamDriver", b =>
                {
                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.HasKey("FantasyTeamId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("FantasyTeamDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoundNumber")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResultDriver", b =>
                {
                    b.Property<int>("RaceResultId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("DidFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("FastestLap")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("RaceResultId", "DriverId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.ToTable("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.TeamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId", "RaceId")
                        .IsUnique();

                    b.ToTable("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("Drivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithOne("FantasyTeam")
                        .HasForeignKey("F1Fantasy.Api.Models.FantasyTeam", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeamDriver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Driver", "Driver")
                        .WithMany("FantasyTeamDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamDrivers")
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Race", "Race")
                        .WithOne("RaceResult")
                        .HasForeignKey("F1Fantasy.Api.Models.RaceResult", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResultDriver", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Constructor", "Constructor")
                        .WithMany("RaceResultDrivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.Driver", "Driver")
                        .WithMany("RaceResultDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.RaceResult", "RaceResult")
                        .WithMany("DriverResults")
                        .HasForeignKey("RaceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Driver");

                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.TeamScore", b =>
                {
                    b.HasOne("F1Fantasy.Api.Models.Race", "Race")
                        .WithMany("TeamScores")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Fantasy.Api.Models.AppUser", "User")
                        .WithMany("TeamScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.AppUser", b =>
                {
                    b.Navigation("FantasyTeam");

                    b.Navigation("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Constructor", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("FantasyTeams");

                    b.Navigation("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Driver", b =>
                {
                    b.Navigation("FantasyTeamDrivers");

                    b.Navigation("RaceResultDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.FantasyTeam", b =>
                {
                    b.Navigation("FantasyTeamDrivers");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.Race", b =>
                {
                    b.Navigation("RaceResult");

                    b.Navigation("TeamScores");
                });

            modelBuilder.Entity("F1Fantasy.Api.Models.RaceResult", b =>
                {
                    b.Navigation("DriverResults");
                });
#pragma warning restore 612, 618
        }
    }
}
